apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

images:
- name: hub.k8s.ucar.edu/afoster/ppeviewer
  newName: hub.k8s.ucar.edu/afoster/ppeviewer
  newTag: b744756
